//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonWebApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllPokemons", ReplyAction="http://tempuri.org/IService1/getAllPokemonsResponse")]
        PokemonWCF.Pokemon[] getAllPokemons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllPokemons", ReplyAction="http://tempuri.org/IService1/getAllPokemonsResponse")]
        System.Threading.Tasks.Task<PokemonWCF.Pokemon[]> getAllPokemonsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllStades", ReplyAction="http://tempuri.org/IService1/getAllStadesResponse")]
        PokemonWCF.Stade[] getAllStades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllStades", ReplyAction="http://tempuri.org/IService1/getAllStadesResponse")]
        System.Threading.Tasks.Task<PokemonWCF.Stade[]> getAllStadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllMatchs", ReplyAction="http://tempuri.org/IService1/getAllMatchsResponse")]
        PokemonWCF.Match[] getAllMatchs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllMatchs", ReplyAction="http://tempuri.org/IService1/getAllMatchsResponse")]
        System.Threading.Tasks.Task<PokemonWCF.Match[]> getAllMatchsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PokemonWebApp.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PokemonWebApp.ServiceReference1.IService1>, PokemonWebApp.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PokemonWCF.Pokemon[] getAllPokemons() {
            return base.Channel.getAllPokemons();
        }
        
        public System.Threading.Tasks.Task<PokemonWCF.Pokemon[]> getAllPokemonsAsync() {
            return base.Channel.getAllPokemonsAsync();
        }
        
        public PokemonWCF.Stade[] getAllStades() {
            return base.Channel.getAllStades();
        }
        
        public System.Threading.Tasks.Task<PokemonWCF.Stade[]> getAllStadesAsync() {
            return base.Channel.getAllStadesAsync();
        }
        
        public PokemonWCF.Match[] getAllMatchs() {
            return base.Channel.getAllMatchs();
        }
        
        public System.Threading.Tasks.Task<PokemonWCF.Match[]> getAllMatchsAsync() {
            return base.Channel.getAllMatchsAsync();
        }
    }
}
